apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-be-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vipulj-devops/app1-backend-config.git
    targetRevision: HEAD
    path: backend 
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-ns
